import cron from 'node-cron';
import { prisma } from './prisma';

export function startAutoOTCron() {
  // Cada hora revisa planes vencidos
  cron.schedule('0 * * * *', generateDueWorkOrders);
  console.log('[Cron] Auto-OT scheduler iniciado');
}

export async function generateDueWorkOrders() {
  const now = new Date();

  const plans = await prisma.maintenancePlan.findMany({
    where: { active: true },
    include: { asset: true },
  });

  const admin = await prisma.user.findFirst({ where: { role: 'ADMIN' } });
  if (!admin) return;

  for (const plan of plans) {
    let isDue = false;

    if (plan.triggerType === 'TIME' || plan.triggerType === 'BOTH') {
      isDue = !!plan.nextDue && plan.nextDue <= now;
    }

    if (plan.triggerType === 'USAGE' || plan.triggerType === 'BOTH') {
      const asset = plan.asset;
      const currentValue =
        plan.usageUnit === 'hours' ? asset.currentHours :
        plan.usageUnit === 'cycles' ? asset.currentCycles :
        plan.usageUnit === 'km' ? asset.currentKm : null;
      if (currentValue !== null && plan.usageThreshold !== null) {
        isDue = isDue || currentValue! >= plan.usageThreshold!;
      }
    }

    if (!isDue) continue;

    // Evitar duplicados: no crear si ya hay OT abierta para este plan
    const existing = await prisma.workOrder.findFirst({
      where: {
        maintenancePlanId: plan.id,
        status: { notIn: ['COMPLETED', 'CANCELLED'] },
      },
    });
    if (existing) continue;

    const ot = await prisma.workOrder.create({
      data: {
        title: `[AUTO] ${plan.name}`,
        description: plan.description ?? `Generado automáticamente desde plan: ${plan.name}`,
        type: plan.type,
        priority: 'MEDIUM',
        status: 'PENDING',
        assetId: plan.assetId,
        createdById: admin.id,
        maintenancePlanId: plan.id,
        scheduledAt: plan.nextDue ?? now,
        autoGenerated: true,
      },
    });

    // Si el plan tiene checklist template, copiar ítems
    if (plan.checklistTemplateId) {
      const template = await prisma.checklistTemplate.findUnique({
        where: { id: plan.checklistTemplateId },
        include: { items: { orderBy: { order: 'asc' } } },
      });
      if (template) {
        const checklist = await prisma.workOrderChecklist.create({ data: { workOrderId: ot.id } });
        await prisma.workOrderChecklistItem.createMany({
          data: template.items.map((item) => ({
            checklistId: checklist.id,
            order: item.order,
            description: item.description,
            required: item.required,
          })),
        });
      }
    }

    // Actualizar nextDue para planes por tiempo
    if ((plan.triggerType === 'TIME' || plan.triggerType === 'BOTH') && plan.frequency && plan.frequencyUnit && plan.nextDue) {
      const next = new Date(plan.nextDue);
      if (plan.frequencyUnit === 'days') next.setDate(next.getDate() + plan.frequency);
      else if (plan.frequencyUnit === 'weeks') next.setDate(next.getDate() + plan.frequency * 7);
      else if (plan.frequencyUnit === 'months') next.setMonth(next.getMonth() + plan.frequency);

      await prisma.maintenancePlan.update({
        where: { id: plan.id },
        data: { nextDue: next, lastGenerated: now },
      });
    }

    console.log(`[AutoOT] Generada OT: ${ot.id} para plan: ${plan.name}`);
  }
}
